package mib

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sleepinggenius2/gosmi"
)

// Every snippet the editor offers must produce a MIB that LOADS.
//
// The `table` snippet did not: it emitted the table and its row and nothing
// else — no SEQUENCE type, so `SYNTAX <name>Entry` referred to nothing; no
// columns; and an INDEX naming an object that did not exist. Inserting it
// produced a MIB that cannot resolve, which is the opposite of what a snippet
// is for, and nothing anywhere said so.
//
// The fixtures under testdata/snippets are the snippets rendered with a name,
// regenerated by hand from frontend/src/mibeditor/tokenize.js when they change.
func TestEverySnippetProducesSomethingThatLoads(t *testing.T) {
	entries, err := os.ReadDir("testdata/snippets")
	if err != nil {
		t.Skip("no snippet fixtures")
	}

	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".snippet") {
			continue
		}
		key := strings.TrimSuffix(e.Name(), ".snippet")

		t.Run(key, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join("testdata/snippets", e.Name()))
			if err != nil {
				t.Fatal(err)
			}
			body := string(raw)

			// A fragment is not a module: wrap the ones that are not already.
			//
			// The `imports` snippet IS an IMPORTS clause — it replaces the one in
			// the file being edited — so it gets a bare wrapper. Adding the usual
			// one would make two clauses, a fault in the test and not the snippet.
			switch {
			case strings.HasPrefix(strings.TrimSpace(body), "IMPORTS"):
				body = "SNIP-MIB DEFINITIONS ::= BEGIN\n" + body +
					"\nparent OBJECT IDENTIFIER ::= { enterprises 99999 }\nEND\n"
			case !strings.Contains(body, "DEFINITIONS"):
				body = "SNIP-MIB DEFINITIONS ::= BEGIN\n" +
					"IMPORTS OBJECT-TYPE, MODULE-IDENTITY, Integer32, Counter32, TimeTicks,\n" +
					"        Gauge32, enterprises FROM SNMPv2-SMI\n" +
					"        TEXTUAL-CONVENTION, DisplayString FROM SNMPv2-TC;\n" +
					"parent OBJECT IDENTIFIER ::= { enterprises 99999 }\n\n" +
					body + "\nEND\n"
			}

			dir := t.TempDir()
			// The real core modules, so an import resolves.
			for _, core := range []string{"SNMPv2-SMI", "SNMPv2-TC"} {
				src, err := os.ReadFile(filepath.Join("../../mibs", core))
				if err != nil {
					t.Skip("no corpus")
				}
				if err := os.WriteFile(filepath.Join(dir, core), src, 0o600); err != nil {
					t.Fatal(err)
				}
			}
			name := "SNIP-MIB"
			if m := moduleNameOf(body); m != "" {
				name = m
			}
			if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
				t.Fatal(err)
			}

			gosmi.Exit()
			gosmi.Init()
			gosmi.SetPath(dir)
			s := NewService(dir)

			resp := s.LoadWithDiagnostics([]string{"SNMPv2-SMI", "SNMPv2-TC", name})
			for _, d := range resp.Diagnostics {
				if d.FileName == name && !d.Success {
					t.Fatalf("does not load: %s", d.Error)
				}
			}

			// Loading is not enough — the semantic pass is what catches a
			// SYNTAX referring to a type nobody defined.
			for _, d := range Analyse(body, Symbols()) {
				if d.Severity == SevError {
					t.Errorf("%s at %d:%d — %s", d.Code, d.Line, d.Column, d.Message)
				}
			}
		})
	}
}

// The table snippet specifically: it must produce a table pkg/mib can read.
func TestTableSnippetProducesAReadableTable(t *testing.T) {
	raw, err := os.ReadFile("testdata/snippets/table.snippet")
	if err != nil {
		t.Skip("no table snippet fixture")
	}
	body := "TBL-MIB DEFINITIONS ::= BEGIN\n" +
		"IMPORTS OBJECT-TYPE, Integer32, enterprises FROM SNMPv2-SMI\n" +
		"        DisplayString FROM SNMPv2-TC;\n" +
		"parent OBJECT IDENTIFIER ::= { enterprises 99998 }\n\n" +
		string(raw) + "\nEND\n"

	dir := t.TempDir()
	for _, core := range []string{"SNMPv2-SMI", "SNMPv2-TC"} {
		src, err := os.ReadFile(filepath.Join("../../mibs", core))
		if err != nil {
			t.Skip("no corpus")
		}
		os.WriteFile(filepath.Join(dir, core), src, 0o600)
	}
	if err := os.WriteFile(filepath.Join(dir, "TBL-MIB"), []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	gosmi.Exit()
	gosmi.Init()
	gosmi.SetPath(dir)
	s := NewService(dir)
	s.LoadWithDiagnostics([]string{"SNMPv2-SMI", "SNMPv2-TC", "TBL-MIB"})

	info, err := s.Table("1.3.6.1.4.1.99998.1")
	if err != nil {
		t.Fatalf("the snippet's table does not resolve as a table: %v", err)
	}
	if len(info.Index) == 0 {
		t.Error("the table has no INDEX")
	}
	if len(info.Columns) < 2 {
		t.Errorf("%d columns; a table with fewer than its index and one value is not useful", len(info.Columns))
	}
	// And its index must decode, which is the whole point of a table.
	got := s.DecodeIndexes(info.Oid, []string{"7"})[0]
	if got.Error != "" {
		t.Errorf("the index does not decode: %s", got.Error)
	}
}
