import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { buildScenes } from './screenshots/scenes.js';

/**
 * The build used to take screenshots of the application for the project site.
 *
 * It is the REAL interface — the same Svelte components, the same stylesheet,
 * the same i18n — with only the Wails bridge replaced. That matters: a mock-up
 * drawn to look like the app drifts from it the first time anything changes,
 * whereas this cannot show a layout the application does not actually produce.
 *
 * `frontend/wailsjs/` is gitignored and regenerated by `wails dev`/`wails build`,
 * so the bridge is swapped by RESOLVER rather than by writing files there: a
 * developer's generated bindings are never touched, and a screenshot build works
 * on a fresh clone that has none.
 *
 * The four import shapes in the codebase are `../wailsjs/…` and `../../wailsjs/…`
 * for both the App bindings and the runtime. They are RELATIVE specifiers, which
 * `resolve.alias` handles inconsistently, so this matches them explicitly.
 */
function stubWailsBridge() {
  const bridge = fileURLToPath(new URL('./screenshots/bridge/App.js', import.meta.url));
  const runtime = fileURLToPath(new URL('./screenshots/bridge/runtime.js', import.meta.url));

  return {
    name: 'snmplens-screenshot-bridge',
    enforce: 'pre',
    resolveId(source) {
      const id = source.replace(/\\/g, '/');
      if (/(^|\/)wailsjs\/go\/main\/App(\.js)?$/.test(id)) return bridge;
      if (/(^|\/)wailsjs\/runtime\/runtime(\.js)?$/.test(id)) return runtime;
      return null;
    },
  };
}

/**
 * Seed localStorage and pick the tab, before the application bundle evaluates.
 *
 * A CLASSIC script in the head, not a module. `stores/settingsStore.js` reads
 * localStorage at module-evaluation time and module scripts are deferred, so
 * seeding from a module would run after the store had already read an empty
 * localStorage — sometimes, depending on the import graph. A classic script in
 * the head runs at parse time, before any of it.
 *
 * The tab is chosen with the application's own keyboard shortcut rather than by
 * clicking a selector or reaching into its state. `activeTab` is a plain local
 * in App.svelte and is not persisted, so there is nothing to seed; Ctrl+1..7 is
 * the public interface for this, and a shortcut does not move when a class name
 * does.
 */
function injectScene() {
  const seeds = JSON.parse(
    readFileSync(fileURLToPath(new URL('./screenshots/bridge/seeds.json', import.meta.url)), 'utf8'),
  );
  const scenes = buildScenes(seeds);

  const TAB_KEY = {
    operations: '1', traps: '2', history: '3', monitor: '4',
    discovery: '5', events: '6', mibeditor: '7',
  };

  return {
    name: 'snmplens-screenshot-scene',
    transformIndexHtml() {
      return [
        {
          tag: 'script',
          injectTo: 'head-prepend',
          children: `
(function () {
  var SCENES = ${JSON.stringify(scenes)};
  var TAB_KEY = ${JSON.stringify(TAB_KEY)};
  var want = new URLSearchParams(location.search).get('scene');
  var s = SCENES.filter(function (x) { return x.name === want; })[0] || SCENES[0];

  window.__SNMPLENS_SCENE__ = s;

  try {
    localStorage.clear();
    for (var k in s.seeds) localStorage.setItem(k, s.seeds[k]);
  } catch (e) {}

  // Tell the capture when the page is worth photographing. Chrome cannot ask,
  // so the page says so by setting a flag the harness polls.
  window.__SNMPLENS_READY__ = false;

  function pickTab() {
    var key = TAB_KEY[s.seeds.snmplens_active_tab] || '1';
    window.dispatchEvent(new KeyboardEvent('keydown', {
      key: key, ctrlKey: true, bubbles: true,
    }));
  }

  // Some things cannot be seeded because they are not state anyone stores: a
  // walk's results live in the component that ran it. Those scenes name the
  // buttons to press, BY THEIR TEXT — a label is what a person would look for,
  // and unlike a class name it does not change when the styling does.
  //
  // A step that finds nothing is skipped rather than failing: the scene then
  // captures whatever it would have captured anyway, which is a duller picture
  // and not a broken one.
  function clickText(text) {
    var nodes = document.querySelectorAll('button, .tab-btn, [role="button"]');
    var loose = null;

    // TWO passes. An exact match anywhere beats a prefix match earlier in the
    // document: searching for "SNMP" with prefix matching alone finds the
    // "SNMP Operations" workspace tab long before the "SNMP" settings tab, and
    // clicks the wrong thing while reporting success.
    for (var i = 0; i < nodes.length; i++) {
      var label = (nodes[i].textContent || '').replace(/\\s+/g, ' ').trim();
      if (label === text) { nodes[i].click(); return true; }
      // The prefix case exists for labels with an adornment after them: the MIB
      // list appends a bundled marker, so "IF-MIB" arrives as "IF-MIB ◆".
      if (loose === null && label.indexOf(text + ' ') === 0) loose = nodes[i];
    }
    if (loose) { loose.click(); return true; }
    return false;
  }

  function runSteps(steps, done, pace) {
    var i = 0;
    var gap = pace || 450;
    (function next() {
      if (i >= steps.length) { setTimeout(done, 700); return; }
      var step = steps[i++];
      // "key:," presses Ctrl+comma; "key:shift+A" adds Shift. Some things have
      // no button at all — the settings dialog is opened by a shortcut and
      // nothing else, and Anonymous Mode CANNOT be seeded: settingsStore.js
      // forces it off on load, deliberately, so the only way in is its own
      // Ctrl+Shift+A.
      if (step.indexOf('key:') === 0) {
        var combo = step.slice(4);
        var shift = combo.indexOf('shift+') === 0;
        window.dispatchEvent(new KeyboardEvent('keydown', {
          key: shift ? combo.slice(6) : combo,
          ctrlKey: true, shiftKey: shift, bubbles: true,
        }));

      // "sel:.entry-header|1" clicks the second element matching a selector.
      // Rows do not have labels worth searching for — a history entry's text is
      // its OID and its duration, and a trap's is a timestamp that moves every
      // run — so repeated things are addressed by position instead.
      } else if (step.indexOf('sel:') === 0) {
        var bar = step.lastIndexOf('|');
        var css = bar > 3 ? step.slice(4, bar) : step.slice(4);
        var at = bar > 3 ? parseInt(step.slice(bar + 1), 10) : 0;
        var els = document.querySelectorAll(css);
        if (els[at]) els[at].click();

      // "type:.search-bar input|ifOperStatus" fills a field.
      //
      // Assigning .value alone would show the text and change nothing: Svelte's
      // bind:value is an "input" listener, so without the event the component's
      // own variable never updates and the tree never filters.
      } else if (step.indexOf('type:') === 0) {
        var cut = step.indexOf('|');
        var field = document.querySelector(step.slice(5, cut));
        if (field) {
          field.focus();
          field.value = step.slice(cut + 1);
          field.dispatchEvent(new Event('input', { bubbles: true }));
        }

      } else {
        clickText(step);
      }
      setTimeout(next, gap);
    })();
  }

  // "?record=1" holds the scene at its opening frame instead of playing it.
  // (No backticks in here: this whole block is itself a template literal, and
  // one would end it.)
  //
  // A still wants the END state and gets there as fast as it can; a clip wants
  // the TRANSITION, and cannot start until the camera is rolling. So in record
  // mode the steps are parked behind __SNMPLENS_PLAY__, which tools/record.mjs
  // calls once the screencast is live, at a pace a person can follow rather
  // than the pace a screenshot wants.
  var recording = new URLSearchParams(location.search).get('record') === '1';

  window.addEventListener('load', function () {
    // Let the application mount and its first bindings resolve, then choose the
    // workspace, then let that workspace's own loads settle.
    setTimeout(function () {
      pickTab();
      setTimeout(function () {
        if (recording) {
          // Parked, and SAYING so: the recorder waits on this flag rather than
          // on a fixed delay, so a slow machine records the same clip as a fast
          // one instead of one that starts halfway through.
          window.__SNMPLENS_ARMED__ = true;
          window.__SNMPLENS_PLAY__ = function (pace) {
            runSteps(s.act || [], function () { window.__SNMPLENS_READY__ = true; }, pace);
          };
          return;
        }
        runSteps(s.act || [], function () { window.__SNMPLENS_READY__ = true; });
      }, 800);
    }, 700);
  });
})();
`,
        },
      ];
    },
  };
}

export default defineConfig({
  plugins: [stubWailsBridge(), injectScene(), svelte()],
  // Its own output directory, so a screenshot build can never be mistaken for
  // the one embedded in the binary.
  build: {
    outDir: 'screenshots/dist',
    emptyOutDir: true,
    // Readable when something renders wrong, and the size does not matter here.
    minify: false,
    sourcemap: false,
  },
});
