import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { buildScenes } from './screenshots/scenes.js';

/**
 * The build used to take screenshots of the application for the project site.
 *
 * It is the REAL interface — the same Svelte components, the same stylesheet,
 * the same i18n — with only the Wails bridge replaced. That matters: a mock-up
 * drawn to look like the app drifts from it the first time anything changes,
 * whereas this cannot show a layout the application does not actually produce.
 *
 * `frontend/wailsjs/` is gitignored and regenerated by `wails dev`/`wails build`,
 * so the bridge is swapped by RESOLVER rather than by writing files there: a
 * developer's generated bindings are never touched, and a screenshot build works
 * on a fresh clone that has none.
 *
 * The four import shapes in the codebase are `../wailsjs/…` and `../../wailsjs/…`
 * for both the App bindings and the runtime. They are RELATIVE specifiers, which
 * `resolve.alias` handles inconsistently, so this matches them explicitly.
 */
function stubWailsBridge() {
  const bridge = fileURLToPath(new URL('./screenshots/bridge/App.js', import.meta.url));
  const runtime = fileURLToPath(new URL('./screenshots/bridge/runtime.js', import.meta.url));

  return {
    name: 'snmplens-screenshot-bridge',
    enforce: 'pre',
    resolveId(source) {
      const id = source.replace(/\\/g, '/');
      if (/(^|\/)wailsjs\/go\/main\/App(\.js)?$/.test(id)) return bridge;
      if (/(^|\/)wailsjs\/runtime\/runtime(\.js)?$/.test(id)) return runtime;
      return null;
    },
  };
}

/**
 * Seed localStorage and pick the tab, before the application bundle evaluates.
 *
 * A CLASSIC script in the head, not a module. `stores/settingsStore.js` reads
 * localStorage at module-evaluation time and module scripts are deferred, so
 * seeding from a module would run after the store had already read an empty
 * localStorage — sometimes, depending on the import graph. A classic script in
 * the head runs at parse time, before any of it.
 *
 * The tab is chosen with the application's own keyboard shortcut rather than by
 * clicking a selector or reaching into its state. `activeTab` is a plain local
 * in App.svelte and is not persisted, so there is nothing to seed; Ctrl+1..7 is
 * the public interface for this, and a shortcut does not move when a class name
 * does.
 */
function injectScene() {
  const seeds = JSON.parse(
    readFileSync(fileURLToPath(new URL('./screenshots/bridge/seeds.json', import.meta.url)), 'utf8'),
  );
  const scenes = buildScenes(seeds);

  const TAB_KEY = {
    operations: '1', traps: '2', history: '3', monitor: '4',
    discovery: '5', events: '6', mibeditor: '7',
  };

  /**
   * Read the director and substitute the two placeholders.
   *
   * Checked afterwards, because String.replace with a STRING pattern replaces
   * only the first occurrence — and when a mention of the placeholder in the
   * file's own header comment consumed it, the code was left reading an
   * identifier that does not exist. The script threw on load, every scene
   * captured the application with no seeds in whatever language the machine is
   * set to, and every capture reported success.
   */
  function director(sceneList, tabKey) {
    const src = readFileSync(
      fileURLToPath(new URL('./screenshots/director.js', import.meta.url)), 'utf8',
    )
      // A function as the replacement, so a `$` inside the JSON is not read as a
      // capture-group reference.
      .replace('__SCENES__', () => JSON.stringify(sceneList))
      .replace('__TAB_KEY__', () => JSON.stringify(tabKey));

    for (const token of ['__SCENES__', '__TAB_KEY__']) {
      if (src.includes(token)) {
        throw new Error(
          `screenshots/director.js still contains ${token} after substitution — `
          + 'it appears more than once, and only the first was replaced.',
        );
      }
    }
    return src;
  }

  return {
    name: 'snmplens-screenshot-scene',
    transformIndexHtml() {
      return [
        {
          tag: 'script',
          injectTo: 'head-prepend',
          children: director(scenes, TAB_KEY),
        },
      ];
    },
  };
}

export default defineConfig({
  plugins: [stubWailsBridge(), injectScene(), svelte()],
  // Its own output directory, so a screenshot build can never be mistaken for
  // the one embedded in the binary.
  build: {
    outDir: 'screenshots/dist',
    emptyOutDir: true,
    // Readable when something renders wrong, and the size does not matter here.
    minify: false,
    sourcemap: false,
  },
});
