import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { buildScenes } from './screenshots/scenes.js';

/**
 * The build used to take screenshots of the application for the project site.
 *
 * It is the REAL interface — the same Svelte components, the same stylesheet,
 * the same i18n — with only the Wails bridge replaced. That matters: a mock-up
 * drawn to look like the app drifts from it the first time anything changes,
 * whereas this cannot show a layout the application does not actually produce.
 *
 * `frontend/wailsjs/` is gitignored and regenerated by `wails dev`/`wails build`,
 * so the bridge is swapped by RESOLVER rather than by writing files there: a
 * developer's generated bindings are never touched, and a screenshot build works
 * on a fresh clone that has none.
 *
 * The four import shapes in the codebase are `../wailsjs/…` and `../../wailsjs/…`
 * for both the App bindings and the runtime. They are RELATIVE specifiers, which
 * `resolve.alias` handles inconsistently, so this matches them explicitly.
 */
function stubWailsBridge() {
  const bridge = fileURLToPath(new URL('./screenshots/bridge/App.js', import.meta.url));
  const runtime = fileURLToPath(new URL('./screenshots/bridge/runtime.js', import.meta.url));

  return {
    name: 'snmplens-screenshot-bridge',
    enforce: 'pre',
    resolveId(source) {
      const id = source.replace(/\\/g, '/');
      if (/(^|\/)wailsjs\/go\/main\/App(\.js)?$/.test(id)) return bridge;
      if (/(^|\/)wailsjs\/runtime\/runtime(\.js)?$/.test(id)) return runtime;
      return null;
    },
  };
}

/**
 * Seed localStorage and pick the tab, before the application bundle evaluates.
 *
 * A CLASSIC script in the head, not a module. `stores/settingsStore.js` reads
 * localStorage at module-evaluation time and module scripts are deferred, so
 * seeding from a module would run after the store had already read an empty
 * localStorage — sometimes, depending on the import graph. A classic script in
 * the head runs at parse time, before any of it.
 *
 * The tab is chosen with the application's own keyboard shortcut rather than by
 * clicking a selector or reaching into its state. `activeTab` is a plain local
 * in App.svelte and is not persisted, so there is nothing to seed; Ctrl+1..7 is
 * the public interface for this, and a shortcut does not move when a class name
 * does.
 */
function injectScene() {
  const seeds = JSON.parse(
    readFileSync(fileURLToPath(new URL('./screenshots/bridge/seeds.json', import.meta.url)), 'utf8'),
  );
  const scenes = buildScenes(seeds);

  const TAB_KEY = {
    operations: '1', traps: '2', history: '3', monitor: '4',
    discovery: '5', events: '6', mibeditor: '7',
  };

  return {
    name: 'snmplens-screenshot-scene',
    transformIndexHtml() {
      return [
        {
          tag: 'script',
          injectTo: 'head-prepend',
          children: `
(function () {
  var SCENES = ${JSON.stringify(scenes)};
  var TAB_KEY = ${JSON.stringify(TAB_KEY)};
  var want = new URLSearchParams(location.search).get('scene');
  var s = SCENES.filter(function (x) { return x.name === want; })[0] || SCENES[0];

  window.__SNMPLENS_SCENE__ = s;

  try {
    localStorage.clear();
    for (var k in s.seeds) localStorage.setItem(k, s.seeds[k]);
  } catch (e) {}

  // Tell the capture when the page is worth photographing. Chrome cannot ask,
  // so the page says so by setting a flag the harness polls.
  window.__SNMPLENS_READY__ = false;

  function pickTab() {
    var key = TAB_KEY[s.seeds.snmplens_active_tab] || '1';
    window.dispatchEvent(new KeyboardEvent('keydown', {
      key: key, ctrlKey: true, bubbles: true,
    }));
  }

  window.addEventListener('load', function () {
    // Let the application mount and its first bindings resolve, then choose the
    // workspace, then let that workspace's own loads settle.
    setTimeout(function () {
      pickTab();
      setTimeout(function () { window.__SNMPLENS_READY__ = true; }, 900);
    }, 700);
  });
})();
`,
        },
      ];
    },
  };
}

export default defineConfig({
  plugins: [stubWailsBridge(), injectScene(), svelte()],
  // Its own output directory, so a screenshot build can never be mistaken for
  // the one embedded in the binary.
  build: {
    outDir: 'screenshots/dist',
    emptyOutDir: true,
    // Readable when something renders wrong, and the size does not matter here.
    minify: false,
    sourcemap: false,
  },
});
