package main

import (
	"bytes"
	"encoding/base64"
	"errors"
	"path/filepath"
	"strings"
	"testing"

	"SnmpLens/pkg/secrets"
)

// The migration's whole premise: Go must open what WebCrypto sealed.
//
// crypto.js writes "enc:" + base64(12-byte IV || GCM output), and Go's
// gcm.Seal with a 12-byte nonce produces the same layout — so adopting the
// key is enough and nothing has to be re-encrypted. If that were wrong, every
// existing user would lose their stored credentials the moment the key moved.
//
// This vector was generated by real WebCrypto (node's webcrypto, same calls as
// crypto.js), NOT by this package. A round trip against ourselves would only
// prove we agree with ourselves.
const (
	webcryptoJWKK      = "-LukSrvgGFYpqPOFYMoFFqpYwcnlDyoM1gXWoAFQuF4"
	webcryptoCommunity = "enc:wcDsDPOc+N2IqXYcRees9HLKwcmXaF9WAr4KywiGceVvcxSUUloMdwNeaJM="
	webcryptoAuthPass  = "enc:Se6oHQuYXaAdL6VBVP2RYvVQoSkNbPqviE1rCGkVcwqiVHecLIm2"
	webcryptoUnicode   = "enc:F5UgM/e6WdeWFfbTQU5FlTvQ8WgU0h4+stW4L4vaZi/gcMu20La6XLymN0wCGP9wh/WMYHP0"
)

func settingsApp(t *testing.T) *App {
	t.Helper()
	store, err := secrets.Open(filepath.Join(t.TempDir(), "secrets"))
	if err != nil {
		t.Fatalf("secrets.Open: %v", err)
	}
	return &App{secrets: store}
}

func TestGoOpensWhatWebCryptoSealed(t *testing.T) {
	a := settingsApp(t)

	if err := a.SettingsAdoptKey(webcryptoJWKK); err != nil {
		t.Fatalf("adopting the legacy key: %v", err)
	}

	got, err := a.SettingsOpen([]string{webcryptoCommunity, webcryptoAuthPass, webcryptoUnicode})
	if err != nil {
		t.Fatalf("opening WebCrypto ciphertext: %v", err)
	}
	want := []string{"s3cr3t-community", "authpass123", "mot-de-passe-accentue-eaeu"}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("value %d = %q, want %q", i, got[i], want[i])
		}
	}
}

// And the other direction, so a value sealed after the migration is still one
// the old code could have produced.
func TestSealOpenRoundTrip(t *testing.T) {
	a := settingsApp(t)

	values := []string{"public", "", "a", strings.Repeat("x", 4096), "accentué ✓"}
	sealed, err := a.SettingsSeal(values)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	for i, s := range sealed {
		if values[i] == "" {
			if s != "" {
				t.Errorf("an empty value was sealed into %q; empty means 'not set'", s)
			}
			continue
		}
		if !strings.HasPrefix(s, "enc:") {
			t.Errorf("value %d was not sealed: %q", i, s)
		}
		raw, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(s, "enc:"))
		if err != nil {
			t.Errorf("value %d is not valid base64: %v", i, err)
			continue
		}
		// Only where a chance match is negligible. A single byte turns up in
		// 28 random ones about one time in ten, so asserting it for "a" tests
		// the random number generator, not the encryption.
		if len(values[i]) >= 4 && bytes.Contains(raw, []byte(values[i])) {
			t.Errorf("value %d appears in its own ciphertext", i)
		}
	}

	opened, err := a.SettingsOpen(sealed)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	for i := range values {
		if opened[i] != values[i] {
			t.Errorf("value %d round-tripped to %q", i, opened[i])
		}
	}
}

// Sealing an already-sealed value would double-encrypt it and lose the
// plaintext for good — settingsStore re-saves the whole object on every change.
func TestSealIsIdempotent(t *testing.T) {
	a := settingsApp(t)
	once, err := a.SettingsSeal([]string{"public"})
	if err != nil {
		t.Fatal(err)
	}
	twice, err := a.SettingsSeal(once)
	if err != nil {
		t.Fatal(err)
	}
	if twice[0] != once[0] {
		t.Fatalf("re-sealing changed the value:\n once: %s\n twice: %s", once[0], twice[0])
	}
	opened, err := a.SettingsOpen(twice)
	if err != nil || opened[0] != "public" {
		t.Errorf("a re-sealed value no longer opens: %q %v", opened, err)
	}
}

// Adopting twice would replace the key that opens the stored blob with one
// that does not, and the failure would look exactly like a corrupt store.
func TestAdoptKeyRefusesToReplaceADifferentKey(t *testing.T) {
	a := settingsApp(t)
	if err := a.SettingsAdoptKey(webcryptoJWKK); err != nil {
		t.Fatal(err)
	}

	other := base64.RawURLEncoding.EncodeToString([]byte(strings.Repeat("k", 32)))
	if err := a.SettingsAdoptKey(other); err == nil {
		t.Error("a second, different key was adopted over the first")
	}

	// Still opens with the original.
	if _, err := a.SettingsOpen([]string{webcryptoCommunity}); err != nil {
		t.Errorf("the original key was damaged: %v", err)
	}
}

// A migration interrupted after the store accepted the key but before the
// browser deleted its copy must be able to finish on the next run.
func TestAdoptKeyIsIdempotentForTheSameKey(t *testing.T) {
	a := settingsApp(t)
	if err := a.SettingsAdoptKey(webcryptoJWKK); err != nil {
		t.Fatal(err)
	}
	if err := a.SettingsAdoptKey(webcryptoJWKK); err != nil {
		t.Errorf("re-adopting the same key failed: %v", err)
	}
	if _, err := a.SettingsOpen([]string{webcryptoCommunity}); err != nil {
		t.Errorf("the key no longer opens the blob: %v", err)
	}
}

func TestAdoptKeyRefusesNonsense(t *testing.T) {
	for _, in := range []string{
		"", "not base64url!!", base64.RawURLEncoding.EncodeToString([]byte("too short")),
		base64.RawURLEncoding.EncodeToString(make([]byte, 16)),
	} {
		a := settingsApp(t)
		if err := a.SettingsAdoptKey(in); err == nil {
			t.Errorf("%q was adopted as a key", in)
		}
	}
}

// With no secret store there is nowhere to put the key, and that must be an
// error the renderer can act on — not a silent fallback to no protection.
func TestNoSecretStoreIsReportedRatherThanWorkedAround(t *testing.T) {
	a := &App{}

	st := a.SettingsKeyStatus()
	if st.Available || st.HasKey {
		t.Errorf("status claims a store: %+v", st)
	}

	if _, err := a.SettingsSeal([]string{"public"}); !errors.Is(err, errNoSecretStore) {
		t.Errorf("Seal error = %v, want errNoSecretStore", err)
	}
	if _, err := a.SettingsOpen([]string{webcryptoCommunity}); !errors.Is(err, errNoSecretStore) {
		t.Errorf("Open error = %v, want errNoSecretStore", err)
	}
	if err := a.SettingsAdoptKey(webcryptoJWKK); !errors.Is(err, errNoSecretStore) {
		t.Errorf("Adopt error = %v, want errNoSecretStore", err)
	}
}

// Status must distinguish "no key yet" from "key unreadable": the first is a
// first run, the second must never lead to sealing under a fresh key.
func TestKeyStatusReportsTheThreeStates(t *testing.T) {
	a := settingsApp(t)

	st := a.SettingsKeyStatus()
	if !st.Available || st.HasKey || st.Error != "" {
		t.Errorf("before any key: %+v", st)
	}
	if st.Backend == "" || st.Backend == "unavailable" {
		t.Errorf("backend not named: %+v", st)
	}

	if _, err := a.SettingsSeal([]string{"public"}); err != nil {
		t.Fatal(err)
	}
	st = a.SettingsKeyStatus()
	if !st.HasKey {
		t.Errorf("after sealing, HasKey is false: %+v", st)
	}
}

// Forgetting the key must actually make the blob unreadable — that is what
// "reset settings" relies on.
func TestForgetKeyMakesSealedValuesUnreadable(t *testing.T) {
	a := settingsApp(t)
	sealed, err := a.SettingsSeal([]string{"public"})
	if err != nil {
		t.Fatal(err)
	}
	if err := a.SettingsForgetKey(); err != nil {
		t.Fatal(err)
	}

	// A fresh App over the same store: no cached key, and none stored.
	fresh := &App{secrets: a.secrets}
	if st := fresh.SettingsKeyStatus(); st.HasKey {
		t.Fatal("the key survived ForgetKey")
	}
	opened, err := fresh.SettingsOpen(sealed)
	if err == nil {
		t.Errorf("the old ciphertext still opened as %q — under a NEW key, which means the value is lost, not readable", opened)
	}
}

// The key must never be stored where the ciphertext is, which is the entire
// point. Assert it is in the secret store and readable only through it.
func TestTheKeyLivesInTheSecretStore(t *testing.T) {
	a := settingsApp(t)
	if _, err := a.SettingsSeal([]string{"public"}); err != nil {
		t.Fatal(err)
	}
	raw, err := a.secrets.Get(secrets.SettingsKeyRef())
	if err != nil {
		t.Fatalf("the key is not under its ref: %v", err)
	}
	key, err := base64.StdEncoding.DecodeString(raw)
	if err != nil || len(key) != 32 {
		t.Errorf("the stored key is not 32 raw bytes: %d, %v", len(key), err)
	}
}

// A Store whose failures we choose.
type stubStore struct {
	values  map[string]string
	getErr  error
	setErr  error
	backend string
	sets    int
}

func (s *stubStore) Get(ref string) (string, error) {
	if s.getErr != nil {
		return "", s.getErr
	}
	v, ok := s.values[ref]
	if !ok {
		return "", secrets.ErrNotFound
	}
	return v, nil
}

func (s *stubStore) Set(ref, secret string) error {
	s.sets++
	if s.setErr != nil {
		return s.setErr
	}
	if s.values == nil {
		s.values = map[string]string{}
	}
	s.values[ref] = secret
	return nil
}

func (s *stubStore) Delete(ref string) error { delete(s.values, ref); return nil }
func (s *stubStore) Backend() string {
	if s.backend == "" {
		return "stub"
	}
	return s.backend
}

// The branch settingsKey's own doc comment is about: a key that cannot be READ
// must not be answered with a new one.
//
// Doing so re-seals the user's credentials under a fresh key while the real
// one sits unreadable, which loses the old ones for good. Mutating the
// ErrNotFound case to `default:` restores exactly that behaviour, and nothing
// in the suite noticed — secrets.Store is an interface, so this is the only
// place it can be pinned.
func TestSettingsKeyRefusesToMintOverAnUnreadableKey(t *testing.T) {
	for _, tc := range []struct {
		name string
		err  error
	}{
		{"locked keychain", errors.New("keychain lookup: exit status 51")},
		{"dpapi refused", errors.New("unprotect: access denied")},
		{"permission denied", errors.New("read sinks.secrets: permission denied")},
	} {
		t.Run(tc.name, func(t *testing.T) {
			store := &stubStore{getErr: tc.err}
			a := &App{secrets: store}

			if _, err := a.SettingsSeal([]string{"public"}); err == nil {
				t.Error("sealing proceeded with an unreadable key")
			}
			if store.sets != 0 {
				t.Errorf("a replacement key was written %d time(s)", store.sets)
			}
			if _, err := a.SettingsOpen([]string{webcryptoCommunity}); err == nil {
				t.Error("opening proceeded with an unreadable key")
			}
			if st := a.SettingsKeyStatus(); st.HasKey || st.Error == "" {
				t.Errorf("status hides the failure: %+v", st)
			}
		})
	}
}

// And the case that MAY mint: genuinely absent.
func TestSettingsKeyMintsWhenGenuinelyAbsent(t *testing.T) {
	store := &stubStore{}
	a := &App{secrets: store}

	sealed, err := a.SettingsSeal([]string{"public"})
	if err != nil {
		t.Fatalf("first use failed: %v", err)
	}
	if store.sets != 1 {
		t.Errorf("wrote the key %d times", store.sets)
	}
	opened, err := a.SettingsOpen(sealed)
	if err != nil || opened[0] != "public" {
		t.Errorf("round trip: %q %v", opened, err)
	}
}

// A value that merely LOOKS sealed must not be passed through as plaintext.
func TestSealDoesNotMistakeAValueForCiphertext(t *testing.T) {
	a := settingsApp(t)

	// A community someone actually chose, that happens to start with the
	// prefix. It used to be written to localStorage verbatim, in the clear,
	// and then failed the entire batch on the next open.
	const tricky = "enc:my-community"
	sealed, err := a.SettingsSeal([]string{tricky})
	if err != nil {
		t.Fatal(err)
	}
	if sealed[0] == tricky {
		t.Fatal("the value was passed through unsealed")
	}
	opened, err := a.SettingsOpen(sealed)
	if err != nil {
		t.Fatalf("it no longer opens: %v", err)
	}
	if opened[0] != tricky {
		t.Errorf("round-tripped to %q", opened[0])
	}
}
