/**
 * Generate the stub Wails bridge used by the screenshot harness.
 *
 * The fixture data is not invented here. It comes from a specification that was
 * produced by reading the real Go structs and their JSON tags — the tags are the
 * contract across the bridge — so the shapes the interface receives are the
 * shapes the backend actually sends. Generating rather than hand-writing means
 * the two cannot drift apart quietly.
 *
 *   node tools/genbridge.mjs <spec.json> [--out frontend/screenshots/bridge]
 *
 * Every binding the frontend imports gets an export, whether the specification
 * covers it or not: a missing export is not a missing feature, it is a module
 * that fails to load and a blank page.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');

const specPath = process.argv[2];
if (!specPath) {
  console.error('usage: node tools/genbridge.mjs <spec.json> [--out <dir>]');
  process.exit(2);
}
const outDir = process.argv.includes('--out')
  ? process.argv[process.argv.indexOf('--out') + 1]
  : join(repo, 'frontend', 'screenshots', 'bridge');

/* --- what the frontend actually imports ---------------------------------- */

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(svelte|js)$/.test(name)) out.push(p);
  }
  return out;
}

const appNames = new Set();
const runtimeNames = new Set();

for (const file of walk(join(repo, 'frontend', 'src'))) {
  const src = readFileSync(file, 'utf8');
  const collect = (re, into) => {
    for (const m of src.matchAll(re)) {
      for (const raw of m[1].split(',')) {
        const n = raw.trim().split(/\s+as\s+/)[0].trim();
        if (n) into.add(n);
      }
    }
  };
  collect(/import\s*\{([^}]*)\}\s*from\s*['"][^'"]*wailsjs\/go\/main\/App['"]/g, appNames);
  collect(/import\s*\{([^}]*)\}\s*from\s*['"][^'"]*wailsjs\/runtime[^'"]*['"]/g, runtimeNames);
}

/* --- the specification --------------------------------------------------- */

const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const areas = (spec.result || spec).areas || [];

// One entry may cover several bindings ("A / B / C"), and several agents may
// describe the same one. Keep the richest example for each.
const fixtures = new Map();
let specified = 0;
let unparsed = 0;

for (const area of areas) {
  for (const b of area.bindings || []) {
    const raw = (b.example || '').trim();
    let value;
    try {
      value = JSON.parse(raw);
    } catch {
      unparsed++;
      continue;
    }
    for (const name of b.name.split('/').map((s) => s.trim()).filter(Boolean)) {
      specified++;
      const prev = fixtures.get(name);
      if (!prev || JSON.stringify(value).length > JSON.stringify(prev).length) {
        fixtures.set(name, value);
      }
    }
  }
}

/* --- defaults for anything the specification did not cover ---------------- */

// Shape matters more than content for these: the interface branches on whether
// it got an array, an object or a string, so returning null everywhere would
// throw somewhere in a `.map`.
const SHAPE_DEFAULTS = [
  [/^(List|Load|Get.*s|.*Query|.*Symbols|.*Variables)/, []],
  [/^Events(Counts)$/, {}],
  [/^(Snmp(Get|Set|Walk|GetNext|GetBulk|SetMultiple|Discover))/, []],
  [/^(Network(Ping|Traceroute))/, []],
  [/^Notify(List)/, []],
  [/^(Mib(Editor)?(List|Symbols))/, []],
  [/^(Get|Secrets|Service|Autostart|Settings|Check|Notify(Default|Preview|Template))/, null],
];

function defaultFor(name) {
  for (const [re, value] of SHAPE_DEFAULTS) if (re.test(name)) return value;
  return null;
}

/* --- emit ---------------------------------------------------------------- */

const lines = [];
lines.push('// GENERATED by tools/genbridge.mjs — do not edit by hand.');
lines.push('//');
lines.push('// The stub Wails bridge for the screenshot harness. Every binding the frontend');
lines.push('// imports has an export here, because a missing one is not a missing feature —');
lines.push('// it is a module that fails to load and a blank page.');
lines.push('//');
lines.push('// The data came from reading the real Go structs and their JSON tags, so what');
lines.push('// the interface receives has the shape the backend actually sends.');
lines.push('');
lines.push('import { scene } from "./scene.js";');
lines.push('import { dynamic, setFixtures } from "./dynamic.js";');
lines.push('');
lines.push('const FIXTURES = ' + JSON.stringify(Object.fromEntries(fixtures), null, 1) + ';');
lines.push('');
lines.push('// A computed answer may want to AMEND a fixture rather than replace it — the');
lines.push('// history list needs a second walk to diff against and the other four entries');
lines.push('// unchanged. Handing dynamic.js the table avoids a second copy of them that');
lines.push('// nothing keeps in step. Not an import, which would be a cycle: App.js already');
lines.push('// imports dynamic.js.');
lines.push('setFixtures(FIXTURES);');
lines.push('');
lines.push('// Three sources, in order: a scene override, a computed answer, a fixture.');
lines.push('// The computed layer exists for things a static example cannot carry — six');
lines.push('// hours of chart points anchored to the present, rather than six hours of');
lines.push('// JSON that drifts out of the visible range a week after it was written.');
lines.push('//');
lines.push('// The ARGUMENTS are forwarded, which they were not: every binding was emitted');
lines.push('// with an empty parameter list, so a computed answer could not depend on what');
lines.push('// was asked. That is not an abstract limitation — GetOidDetails is called once');
lines.push('// per varbind, and answering the same fixture to all of them put the word');
lines.push('// "linkDown" in the Name column of every row of the trap screenshot, beside six');
lines.push('// OIDs that are plainly six different objects.');
lines.push('function resolve(name, args) {');
lines.push('  const over = scene().bindings || {};');
lines.push('  if (Object.prototype.hasOwnProperty.call(over, name)) return over[name];');
lines.push('  if (typeof dynamic[name] === "function") {');
lines.push('    // undefined means NO OPINION, and falls through to the fixture. A');
lines.push('    // computed answer that only knows about some inputs — GetOidDetails knows');
lines.push('    // the OIDs in the fixtures and no others — needs a way to decline without');
lines.push('    // that decline becoming the answer.');
lines.push('    const computed = dynamic[name](...(args || []));');
lines.push('    if (computed !== undefined) return computed;');
lines.push('  }');
lines.push('  if (Object.prototype.hasOwnProperty.call(FIXTURES, name)) return FIXTURES[name];');
lines.push('  return null;');
lines.push('}');
lines.push('');
lines.push('// A scene may declare how long a call takes. Every binding answered on the next');
lines.push('// microtask, which is right for a still — it wants the end state as fast as it');
lines.push('// can get there — and leaves a CLIP with nothing to film: the button never');
lines.push('// shows that it is working, and 155 varbinds land in the same frame as the');
lines.push('// click that asked for them. Stills are unaffected either way, because virtual');
lines.push('// time spends the timer instantly.');
lines.push('function answer(name, args) {');
lines.push('  const value = resolve(name, args);');
lines.push('  const ms = (scene().latency || {})[name];');
lines.push('  return ms ? new Promise((r) => setTimeout(() => r(value), ms)) : value;');
lines.push('}');
lines.push('');

const covered = [];
const filled = [];
for (const name of [...appNames].sort()) {
  if (fixtures.has(name)) covered.push(name);
  else filled.push(name);
  const fallback = fixtures.has(name) ? '' : ` ?? ${JSON.stringify(defaultFor(name))}`;
  lines.push(`export async function ${name}(...a) { return answer(${JSON.stringify(name)}, a)${fallback}; }`);
}

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'App.js'), lines.join('\n') + '\n');

/* --- the runtime -------------------------------------------------------- */

const rt = [];
rt.push('// GENERATED by tools/genbridge.mjs — do not edit by hand.');
rt.push('//');
rt.push('// The Wails runtime, stubbed. EventsOn is the interesting one: a scene can');
rt.push('// script payloads to arrive after the page has settled, which is how a trap');
rt.push('// listener looks alive in a still image rather than merely switched on.');
rt.push('');
rt.push('import { scene } from "./scene.js";');
rt.push('import { FEEDS } from "./feed.js";');
rt.push('');
rt.push('const handlers = new Map();');
rt.push('');
rt.push('export function EventsOn(name, fn) {');
rt.push('  handlers.set(name, [...(handlers.get(name) || []), fn]);');
rt.push('  const scripted = (scene().events || []).filter((e) => e.name === name);');
rt.push('  for (const e of scripted) {');
rt.push('    setTimeout(() => fn(e.payload), e.afterMs ?? 60);');
rt.push('  }');
rt.push('  startFeed();');
rt.push('  return () => EventsOff(name);');
rt.push('}');
rt.push('');
rt.push('export function EventsOff(name) { handlers.delete(name); }');
rt.push('');
rt.push('/**');
rt.push(' * A scene may declare a FEED: an event that keeps arriving rather than one');
rt.push(' * scripted to arrive once. `scene().events` says "a trap at four seconds",');
rt.push(' * which is right for a still; it cannot say "a sample per series, every');
rt.push(' * interval, for as long as anyone is watching", and that is the whole subject');
rt.push(' * of the monitoring screen.');
rt.push(' *');
rt.push(' * Started from EventsOn rather than at module load, because a feed with no');
rt.push(' * subscriber is a timer nobody reads — and started ONCE however many');
rt.push(' * subscribers register.');
rt.push(' */');
rt.push('let feeding = null;');
rt.push('function startFeed() {');
rt.push('  const cfg = scene().feed;');
rt.push('  if (!cfg || feeding || typeof FEEDS[cfg.from] !== "function") return;');
rt.push('  let tick = 0;');
rt.push('  feeding = setInterval(() => {');
rt.push('    for (const ev of FEEDS[cfg.from](tick++) || []) {');
rt.push('      for (const fn of handlers.get(ev.name) || []) {');
rt.push('        // One handler throwing must not stop the feed for the rest.');
rt.push('        try { fn(ev.payload); } catch (e) { /* keep feeding */ }');
rt.push('      }');
rt.push('    }');
rt.push('  }, cfg.everyMs || 500);');
rt.push('}');
rt.push('');
for (const name of [...runtimeNames].sort()) {
  if (name === 'EventsOn' || name === 'EventsOff') continue;
  if (name === 'IsNotificationAvailable') {
    rt.push(`export function ${name}() { return Promise.resolve(true); }`);
  } else {
    rt.push(`export function ${name}() {}`);
  }
}
writeFileSync(join(outDir, 'runtime.js'), rt.join('\n') + '\n');

/* --- the localStorage seeds --------------------------------------------- */

// The stores read localStorage at MODULE-EVALUATION time, before anything can be
// awaited, so these have to be written before the bundle runs — see the
// transformIndexHtml injector in vite.screenshots.config.js.
const seeds = {};
for (const area of areas) {
  for (const s of area.seeds || []) {
    if (!s.key || /^\(/.test(s.key)) continue; // "(none for ...)" is prose, not a key
    const prev = seeds[s.key];
    if (!prev || String(s.value).length > String(prev).length) seeds[s.key] = s.value;
  }
}
writeFileSync(join(outDir, 'seeds.json'), JSON.stringify(seeds, null, 1) + '\n');

/* --- report -------------------------------------------------------------- */

console.log(`bindings imported by the frontend: ${appNames.size}`);
console.log(`  with fixture data from the spec:  ${covered.length}`);
console.log(`  falling back to a shape default:  ${filled.length}`);
if (unparsed) console.log(`spec entries whose example was not JSON: ${unparsed} (skipped)`);
console.log(`runtime exports: ${runtimeNames.size}`);
console.log(`localStorage seeds: ${Object.keys(seeds).length}`);
console.log();
console.log('no fixture data (shape default only):');
for (const n of filled) console.log('  -', n);
